@baseUrl = http://localhost:1100/api/v1

### Đăng nhập và lấy token
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "userName": "Urban_Hodkiewicz72",
  "password": "ROnaldo11nbk.."
}
###


// Product Api

GET {{baseUrl}}/product
